services:
    app:
        container_name: MicroCMS
        image: php:8.4-apache
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - APP_ENV=dev
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - micro_data:/var/www/html
            - .:/var/www/html
        restart: always
    
volumes:
    micro_data:
